Learning Numpy

In [2]:
import numpy as np

creating array from list

In [6]:
arr_1d = np.array([1, 2, 3, 4, 5]) #1D array(vector)
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) #2D array(matrix)
print("2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


List vs numpy array

In [7]:
py_list = [1, 2, 3, 4, 5] #Python list
print("Python list multiplication:", py_list * 2)

np_array = np.array([1, 2, 3, 4, 5]) #NumPy array
print("NumPy array multiplication:", np_array * 2)

Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy array multiplication: [ 2  4  6  8 10]


Creating arrays from scratch

In [9]:
zeros = np.zeros((2, 3)) #2D array of zeros(2 rows, 3 columns)
print("2D Array of Zeros:\n", zeros)

ones = np.ones((2, 3)) #2D array of ones(2 rows, 3 columns)
print("2D Array of Ones:\n", ones)

full = np.full((2, 3), 7) #2D array filled with a constant value 7 (2 rows, 3 columns)
print("2D Array filled with 7:\n", full)

random = np.random.random((2, 3)) #2D array of random floats (2 rows, 3 columns)
print("2D Array of Random Floats:\n", random)

sequence = np.arange(0, 10, 2) #1D array with a sequence of numbers from 0 to 10 with a step of 2
print("1D Array with Sequence from 0 to 10 with step 2:", sequence)

2D Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
2D Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
2D Array filled with 7:
 [[7 7 7]
 [7 7 7]]
2D Array of Random Floats:
 [[0.30132658 0.11791289 0.96847363]
 [0.76194944 0.07965563 0.76813065]]
1D Array with Sequence from 0 to 10 with step 2: [0 2 4 6 8]


Vector, Matrix & Tensor

In [10]:
vector = np.array([1, 2, 3]) #1D array(vector)
print("1D Array (Vector):", vector)

matrix = np.array([[1, 2], [3, 4]]) #2D array(matrix)
print("2D Array (Matrix):\n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]]) #multidimensionnal array(tensor)
print("Multidimensional Array (Tensor):\n", tensor)

1D Array (Vector): [1 2 3]
2D Array (Matrix):
 [[1 2]
 [3 4]]
Multidimensional Array (Tensor):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Properties of Array

In [12]:
arr = np.array([1, 2, 3, 4, 5]) 

print("Shape of arr:", arr.shape) #shape of the array
print("Data type of arr:", arr.dtype) #data type of the array
print("Size of arr:", arr.size) #size of the array
print("Number of dimensions of arr:", arr.ndim) #number of dimensions of the array

Shape of arr: (5,)
Data type of arr: int32
Size of arr: 5
Number of dimensions of arr: 1


Reshaping of Array

In [13]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
