Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:5])  # Slicing from index 2 to 4
print("Slicing with step", arr[1:8:2])  # Slicing from index 1 to 7 with a step of 2
print("Slicing with negative indices", arr[-5:-2])  # Slicing from index -5 to -3

Basic Slicing [3 4 5]
Slicing with step [2 4 6 8]
Slicing with negative indices [6 7 8]


In [3]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])  # Accessing element at row 1, column 2(Here rows and columns start from 0)
print("entire row", arr_2d[1])  # Accessing entire row at index 1
print("entire column", arr_2d[:, 1])  # Accessing entire column at index 1(: means selecting all availaible rows)

Specific element 6
entire row [4 5 6]
entire column [2 5 8]


Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 2, 5])
print("Sorted array", np.sort(unsorted))  # Sorting the array

arr_2d_unsorted = np.array([[3, 1, 4],
                            [2, 5, 6],
                            [9, 7, 8]])
print("Sorted 2D array along axis 0", np.sort(arr_2d_unsorted, axis=0))  # Sorting along columns(commonly used)
print("Sorted 2D array along axis 1", np.sort(arr_2d_unsorted, axis=1))  # Sorting along rows

Sorted array [1 2 3 4 5]
Sorted 2D array along axis 0 [[2 1 4]
 [3 5 6]
 [9 7 8]]
Sorted 2D array along axis 1 [[1 3 4]
 [2 5 6]
 [7 8 9]]


Filtering

In [6]:
numbers = np.array([1, 2, 3, 4, 5])
even_numbers = numbers[numbers % 2 == 0]  #even numbers
print("Even numbers from the array", even_numbers)  # Filtering even numbers
odd_numbers = numbers[numbers % 2 != 0]  #odd numbers
print("Odd numbers from the array", odd_numbers)  # Filtering odd numbers

Even numbers from the array [2 4]
Odd numbers from the array [1 3 5]


Filtering with mask

In [9]:
mask = numbers > 2
print("Mask for numbers greater than 2", numbers[mask])  # Creating a mask for numbers greater than 2

Mask for numbers greater than 2 [3 4 5]


Adding & Removing data

In [11]:
#adding(combining)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenated array", np.concatenate((arr1, arr2)))  # Concatenating two arrays

#deleting(removing)
arr = np.array([1, 2, 3, 4, 5])
print("Array after deleting element at index 2", np.delete(arr, 2))  # Deleting element at index 2

Concatenated array [1 2 3 4 5 6]
Array after deleting element at index 2 [1 2 4 5]
